# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

uses: actions/checkout@v2
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2
- name: Log in to container registry
uses: docker/login-action@v2
with:
registry: https://index.docker.io/v1/
username: ${{
secrets.AzureAppService_ContainerUsername_aaa07ab7057541748b79e07390bd9ed0 }}
password: ${{
secrets.AzureAppService_ContainerPassword_f4492f67520e4da6ba8258c0d107c282 }}
- name: Build and push container image to registry
uses: docker/build-push-action@v3

uses: actions/checkout@v2
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@v2
- name: Log in to container registry
uses: docker/login-action@v2
with:
registry: https://index.docker.io/v1/
username: ${{
secrets.AzureAppService_ContainerUsername_aaa07ab7057541748b79e07390bd9ed0 }}
password: ${{
secrets.AzureAppService_ContainerPassword_f4492f67520e4da6ba8258c0d107c282 }}
- name: Build and push container image to registry
uses: docker/build-push-action@v3
with:
context: .
push: true
tags: index.docker.io/${{
secrets.AzureAppService_ContainerUsername_aaa07ab7057541748b79e07390bd9ed0
}}/hrb1989/javasp1:${{ github.sha }}
file: ./Dockerfile
deploy:
runs-on: ubuntu-latest
needs: build
environment:
name: 'production'
url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
steps:
- name: Deploy to Azure Web App
id: deploy-to-webapp
uses: azure/webapps-deploy@v2
with:
app-name: 'shell7SB1'
slot-name: 'production'
publish-profile: ${{
secrets.AzureAppService_PublishProfile_0425239420454e2d87725d19a92feb3d }}
images: 'index.docker.io/${{
secrets.AzureAppService_ContainerUsername_aaa07ab7057541748b79e07390bd9ed0
}}/hrb1989/javasp1:${{ github.sha }}
